// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy1Td2Lx5gD7uiACtRrsV3BNCm8HUfQas',
    appId: '1:119919446796:web:dc526c82a10a225191d729',
    messagingSenderId: '119919446796',
    projectId: 'mycompany-11552',
    authDomain: 'mycompany-11552.firebaseapp.com',
    databaseURL: 'https://mycompany-11552-default-rtdb.firebaseio.com',
    storageBucket: 'mycompany-11552.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWElgdgv15IQE3RsnuSU_dqBYtByUkd8',
    appId: '1:119919446796:android:b6b34387601074e691d729',
    messagingSenderId: '119919446796',
    projectId: 'mycompany-11552',
    databaseURL: 'https://mycompany-11552-default-rtdb.firebaseio.com',
    storageBucket: 'mycompany-11552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG71mbzJ73r96tfL1T_mIY81LIxk6xgjA',
    appId: '1:119919446796:ios:aa506349ef37d42491d729',
    messagingSenderId: '119919446796',
    projectId: 'mycompany-11552',
    databaseURL: 'https://mycompany-11552-default-rtdb.firebaseio.com',
    storageBucket: 'mycompany-11552.appspot.com',
    androidClientId: '119919446796-rfkuup3vvgp81d3o0sknd8e14rsdi8i4.apps.googleusercontent.com',
    iosClientId: '119919446796-6kde4fi2nneppmmvvvbjolksni2a4tr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mycompany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG71mbzJ73r96tfL1T_mIY81LIxk6xgjA',
    appId: '1:119919446796:ios:aa506349ef37d42491d729',
    messagingSenderId: '119919446796',
    projectId: 'mycompany-11552',
    databaseURL: 'https://mycompany-11552-default-rtdb.firebaseio.com',
    storageBucket: 'mycompany-11552.appspot.com',
    androidClientId: '119919446796-rfkuup3vvgp81d3o0sknd8e14rsdi8i4.apps.googleusercontent.com',
    iosClientId: '119919446796-6kde4fi2nneppmmvvvbjolksni2a4tr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mycompany',
  );
}
